dist: trusty
sudo: false

language: node_js
node_js:
  - "12"

addons:
  chrome: stable
  apt:
    update: true
    packages:
      - gettext-base

env:
  global:
    CODECOV_TOKEN=$CODECOV_TOKEN

cache:
  directories:
     - ./node_modules

install:
  - npm install

stages:
  - name: Lint & Test
  - name: Deploy to Firebase
    if: branch = master

jobs:
  include:
    - stage: Lint & Test
      script:
        - npm run lint

    - stage: Lint & Test
      script:
        - npm run test -- --no-watch --no-progress --code-coverage --browsers=ChromeHeadless
      after_script:
        - if [[ "$TRAVIS_TEST_RESULT" == 0 ]]; then ./node_modules/.bin/codecov; fi

    - stage: Deploy to Firebase
      skip_cleanup: true
      script:
        - npm run build -- --prod
      before_deploy:
        - envsubst < ./src/assets/env.template.js > ./src/assets/env.js 
      deploy:
        provider: firebase
        token: $FIREBASE_TOKEN
        edge: true
